import Head from "next/head";
import "../styles/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0";

function MyApp({ Component, pageProps }) {
  return (
    <UserProvider
      domain={process.env.AUTH0_DOMAIN}
      clientId={process.env.AUTH0_CLIENT_ID}
      redirectUri={process.env.AUTH0_REDIRECT}
    >
      <Head>
        <title>EverCent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:wght@700&family=Arima+Madurai:wght@500&family=Cinzel:wght@600&family=Raleway:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Component {...pageProps} />
    </UserProvider>
  );
}

export default MyApp;
